version: '3.8'

services:
  stun-server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
    command: ["sh", "-c", "redis-server --daemonize yes && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"]

  peer1:
    build: ./client
    environment:
      - USERNAME=dev1
      - PORT=5000
    volumes:
      - ./client:/app
      - ./shared-files:/app/received_files
    stdin_open: true
    tty: true

  peer2:
    build: ./client
    environment:
      - USERNAME=dev2
      - PORT=5001
    volumes:
      - ./client:/app
      - ./shared-files:/app/received_files
    stdin_open: true
    tty: true